#!/bin/bash
git fetch
git add .
git status
read -p "Do you want to push all the changes to github?[Y/N] " -n 1 -r
# echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    git commit -m "test"
    git push github master
fi
